security audit set up
ansible-collections/netapp.ontap pull request #74
Opened 2022-06-08 19:11 UTC by gikuluca

2022-06-10 17:11 UTC, lonico requested changes
thank you for adding this feature.

2022-06-10 17:11 UTC, lonico commented on plugins/modules/na_ontap_security_audit.py
> +        attributes = {'cli': False, 'http': False, 'ontapi':False}
If the API allows it, I would only set the values that have changed.   This is to preserve idempotency.
eg
```
body = {}
for option in ('cli', 'http', 'ontapi'):
    value =  self.parameters.get(option)
    if value is not None:
        body[option] = value

2022-06-10 17:11 UTC, lonico commented on plugins/modules/na_ontap_security_audit.py
> +  #      if self.na_helper.changed and not self.module.check_mode:
This is needed.  In check_mode, we don't want to make any actual change.

2022-06-10 17:11 UTC, lonico commented on plugins/modules/na_ontap_security_audit.py
> +        if cd_action == 'create' or cd_action is None:
I don't think create makes sense here.   We need to look for modify
```
current = self.get_securiy_audit()
modify = self.na_helper.get_modified_attributes(current, self.parameters)
if self.na_helper.changed and not self.module.check_mode:
    self.patch_security_audit(modify)

2022-06-10 17:11 UTC, lonico commented on plugins/modules/na_ontap_security_audit.py
> +    main()
Better to have a newline.  vscode (and other IDEs) can add it automatically.

2022-06-10 17:14 UTC, lonico commented
Also, unit tests are required.
Look at
https://github.com/ansible-collections/netapp.ontap/blob/main/tests/unit/plugins/modules/test_na_ontap_autosupport.py
for a simple example 
and
https://github.com/ansible-collections/netapp.ontap/blob/main/tests/unit/plugins/modules/test_na_ontap_user_dicts.py
for a more complex one.

2022-06-28 14:10 UTC, gikuluca commented
> Also, unit tests are required. Look at https://github.com/ansible-collections/netapp.ontap/blob/main/tests/unit/plugins/modules/test_na_ontap_autosupport.py for a simple example and https://github.com/ansible-collections/netapp.ontap/blob/main/tests/unit/plugins/modules/test_na_ontap_user_dicts.py for a more complex one.

Hello, thank you for your review.
Actually, i m have written this tests but when i try to execute them with :
`~/.ansible/collections/ansible_collections/netapp/ontap$ ansible-test units --venv --python 3.8 ".*test_na_ontap_security_audit.*" -v --debug
`
<details><summary>Output</summary><blockquote>
`
Using existing Python 3.8 virtual environment: /home/gluca/.ansible/collections/ansible_collections/netapp/ontap/tests/output/.tmp/delegation/python3.8
Run command: /usr/bin/env ANSIBLE_TEST_CONTENT_ROOT=/home/gluca/.ansible/collections/ansible_collections/netapp/ontap LC_ALL=en_US.UTF-8 /tmp/tmp0iiam_tl/python3.8 /home/gluca/.ansible/collections/ansible_collections/netapp/ontap/ ...
Run command: /home/gluca/.ansible/collections/ansible_collections/netapp/ontap/tests/output/.tmp/delegation/python3.8/bin/python -m pip.__main__ install --disable-pip-version-check -c /tmp/tmpx5s6zpu6/ansible_test/_data/requiremen ...
...
Unit test with Python 3.8
Run command: pytest --boxed -r a -n auto --color yes -p no:cacheprovider -c /tmp/tmpx5s6zpu6/ansible_test/_data/pytest.ini --junit-xml /home/gluca/.ansible/collections/ansible_collections/netapp/ontap/tests/output/junit/python3.8- ...
=========================================================================================================== test session starts ===========================================================================================================
platform linux -- Python 3.8.10, pytest-7.1.2, pluggy-1.0.0 -- /home/gluca/.ansible/collections/ansible_collections/netapp/ontap/tests/output/.tmp/delegation/python3.8/bin/python
rootdir: /tmp/tmpx5s6zpu6/ansible_test/_data, configfile: pytest.ini
plugins: forked-1.4.0, mock-3.8.1, xdist-2.5.0
[gw0] linux Python 3.8.10 cwd: /home/gluca/.ansible/collections/ansible_collections/netapp/ontap
[gw1] linux Python 3.8.10 cwd: /home/gluca/.ansible/collections/ansible_collections/netapp/ontap
[gw2] linux Python 3.8.10 cwd: /home/gluca/.ansible/collections/ansible_collections/netapp/ontap
[gw3] linux Python 3.8.10 cwd: /home/gluca/.ansible/collections/ansible_collections/netapp/ontap
[gw4] linux Python 3.8.10 cwd: /home/gluca/.ansible/collections/ansible_collections/netapp/ontap
[gw5] linux Python 3.8.10 cwd: /home/gluca/.ansible/collections/ansible_collections/netapp/ontap
[gw6] linux Python 3.8.10 cwd: /home/gluca/.ansible/collections/ansible_collections/netapp/ontap
[gw7] linux Python 3.8.10 cwd: /home/gluca/.ansible/collections/ansible_collections/netapp/ontap
[gw0] Python 3.8.10 (default, Mar 15 2022, 12:22:08)  -- [GCC 9.4.0]
[gw1] Python 3.8.10 (default, Mar 15 2022, 12:22:08)  -- [GCC 9.4.0]
[gw2] Python 3.8.10 (default, Mar 15 2022, 12:22:08)  -- [GCC 9.4.0]
[gw3] Python 3.8.10 (default, Mar 15 2022, 12:22:08)  -- [GCC 9.4.0]
[gw4] Python 3.8.10 (default, Mar 15 2022, 12:22:08)  -- [GCC 9.4.0]
[gw5] Python 3.8.10 (default, Mar 15 2022, 12:22:08)  -- [GCC 9.4.0]
[gw6] Python 3.8.10 (default, Mar 15 2022, 12:22:08)  -- [GCC 9.4.0] 
[gw7] Python 3.8.10 (default, Mar 15 2022, 12:22:08)  -- [GCC 9.4.0]   
gw0 [4] / gw1 [4] / gw2 [4] / gw3 [4] / gw4 [4] / gw5 [4] / gw6 [4] / gw7 [4]
scheduling tests via LoadScheduling

../../../../../../../tmp/tmpx5s6zpu6/ansible_test/_data/::test_module_fail_when_required_args_missing 
../../../../../../../tmp/tmpx5s6zpu6/ansible_test/_data/::test_rest_missing_arguments 
../../../../../../../tmp/tmpx5s6zpu6/ansible_test/_data/::test_get_security_audit 
../../../../../../../tmp/tmpx5s6zpu6/ansible_test/_data/::test_apply_security_audit 
[gw0] [ 25%] PASSED ../../../../../../../tmp/tmpx5s6zpu6/ansible_test/_data/::test_module_fail_when_required_args_missing 
[gw1] [ 50%] PASSED ../../../../../../../tmp/tmpx5s6zpu6/ansible_test/_data/::test_rest_missing_arguments 
[gw2] [ 75%] PASSED ../../../../../../../tmp/tmpx5s6zpu6/ansible_test/_data/::test_get_security_audit 
[gw3] [100%] FAILED ../../../../../../../tmp/tmpx5s6zpu6/ansible_test/_data/::test_apply_security_audit 
[gw3] [100%] ERROR ../../../../../../../tmp/tmpx5s6zpu6/ansible_test/_data/::test_apply_security_audit 

================================================================================================================= 
ERRORS ==================================================================================================================
_____________________________________________________________________________________________ 
ERROR at teardown of test_apply_security_audit ______________________________________________________________________________________________
[gw3] linux -- Python 3.8.10 /home/gluca/.ansible/collections/ansible_collections/netapp/ontap/tests/output/.tmp/delegation/python3.8/bin/python
request = <SubRequest 'patch_request_and_invoke' for <Function test_apply_security_audit>>

    @pytest.fixture(autouse=True)
    def patch_request_and_invoke(request):
        if DEBUG:
            print('entering patch_request_and_invoke fixture for', request.function)
        function_name = request.function.__name__
    
        with patch('ansible_collections.netapp.ontap.plugins.module_utils.netapp.OntapRestAPI.send_request') as mock_send_request:
            mock_send_request.side_effect = partial(_mock_netapp_send_request, function_name)
            if netapp_utils.has_netapp_lib():
                with patch('ansible_collections.netapp.ontap.plugins.module_utils.netapp.OntapZAPICx.invoke_elem') as mock_invoke_elem:
                    mock_invoke_elem.side_effect = partial(_mock_netapp_invoke_elem, function_name)
                    yield mock_send_request, mock_invoke_elem
            else:
                yield mock_send_request
    
        # This part is executed after the test completes
>       _patch_request_and_invoke_exit_checks(function_name)

tests/unit/framework/mock_rest_and_zapi_requests.py:46: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

function_name = 'test_apply_security_audit'

    def _patch_request_and_invoke_exit_checks(function_name):
        # action to be performed afther a test is complete
        if DEBUG:
            print('exiting patch_request_and_invoke fixture for', function_name)
        if FORCE_REGISTRATION:
            assert function_name in _RESPONSES, 'Error: responses for ZAPI invoke or REST send requests are not registered.'
        # make sure all expected requests were consumed
        if _RESPONSES.get(function_name):
            print('Error: not all responses were processed.  It is expected if the test failed.')
            print('Error: remaining responses: %s' % _RESPONSES[function_name])
            msg = 'Error: not all responses were processed.  Use -s to see detailed error.  '\
                  'Ignore this error if there is an earlier error in the test.'
>           assert not _RESPONSES.get(function_name), msg
E           AssertionError: Error: not all responses were processed.  Use -s to see detailed error.  Ignore this error if there is an earlier error in the test.

tests/unit/framework/mock_rest_and_zapi_requests.py:260: AssertionError
---------------------------------------------------------------------------------------------------------- Captured stdout setup ----------------------------------------------------------------------------------------------------------
entering patch_request_and_invoke fixture for <function test_apply_security_audit at 0x7f09b7e5ab80>
---------------------------------------------------------------------------------------------------------- Captured stdout call -----------------------------------------------------------------------------------------------------------
Inside mock_netapp_send_request [...]

2022-07-25 18:31 UTC, lonico requested changes

2022-07-25 18:31 UTC, lonico commented on plugins/modules/na_ontap_security_audit.py
> +version_added: 2.6.0
this should be 21.22.0

2022-07-25 18:31 UTC, lonico commented on plugins/modules/na_ontap_security_audit.py
> +- Enable or disable ontap,cli,http for security audit
space after ,
ontap, cli, http

2022-07-25 18:31 UTC, lonico commented on plugins/modules/na_ontap_security_audit.py
> +    ontapi: True
We already use this as an int in another context.  I see two options:
1. rename the variables to audit_cli, audit_http, audit_ontapi.    I think this also makes the semantics more explicit.
2. create a dict of dicts.
```
security_audit:
  cli: true/false
  http: true/false
  ontapi: true/false
```
I think the first option is simpler, but you'll need to simple mapping between the API key names and the parameters keys.
With the second option, you could directly map to the REST interface.

2022-07-25 18:31 UTC, lonico commented on plugins/modules/na_ontap_security_audit.py
> +from ansible_collections.netapp.ontap.plugins.module_utils.netapp import OntapRestAPI
not needed
It's simpler to use netapp_utils.OntapRestAPI when needed later

2022-07-25 18:31 UTC, lonico commented on plugins/modules/na_ontap_security_audit.py
> +
one extra line

2022-07-25 18:31 UTC, lonico commented on plugins/modules/na_ontap_security_audit.py
> +class NetAppONTAPSecurityAudit(object):
(object) is not needed from python 3.  And not needed because of `__metaclass__ = type` with python 2.x.

This should read:
```
class NetAppONTAPSecurityAudit:

2022-07-25 18:31 UTC, lonico commented on plugins/modules/na_ontap_security_audit.py
> +        cli=dict(required=False, type='bool'),
audit_cli, audit_http, audit_ontapi

2022-07-25 18:31 UTC, lonico commented on plugins/modules/na_ontap_security_audit.py
> +    self.rest_api = OntapRestAPI(self.module)
netapp_utils.OntapRestAPI

2022-07-25 18:31 UTC, lonico commented on plugins/modules/na_ontap_security_audit.py
> +        value = record.get(f"{element}get")
`f"{element}get"`  why are you doing this?  
From what I see the API returns
```
{
  "cli": true,
  "http": true,
  "ontapi": true
}

Also, we still need to support 2.6 and 2.7, so I'm not sure f strings are supported.  Or you need to explicitly check for the python version and document the minimum version you want to support.

2022-07-25 18:31 UTC, lonico commented on plugins/modules/na_ontap_security_audit.py
> +    message, error = rest_generic.patch_async(self.rest_api, self.api,None, m)
space after comma

2022-07-25 18:31 UTC, lonico commented on plugins/modules/na_ontap_security_audit.py
> +  def patch_security_audit(self, m):
minimum of 3 characters for name, eg modify

2022-07-25 18:31 UTC, lonico commented on tests/unit/plugins/modules/test_na_ontap_security_audit.py
> +class MockONTAPConnection():
you should not need this:
1. this is only for ZAPI
2. this is now deprecated, we're using something similar as what we do for REST.

2022-07-25 18:31 UTC, lonico commented on tests/unit/plugins/modules/test_na_ontap_security_audit.py
> +def get_asup_mock_object(cx_type='zapi', kind=None):
not needed.  Only for ZAPI and deprecated.

2022-07-25 18:31 UTC, lonico commented on tests/unit/plugins/modules/test_na_ontap_security_audit.py
> +          "cliget": true,
This does not match the API:
```
{
  "cli": true,
  "http": true,
  "ontapi": true
}

2022-07-25 18:31 UTC, lonico commented on tests/unit/plugins/modules/test_na_ontap_security_audit.py
> +SRR = {
We have a new method:

```
from ansible_collections.netapp.ontap.tests.unit.framework.rest_factory import rest_responses
...

SRR = rest_responses({
  'get_response_all_true': (
    200,
    {
...
```

All the generic answers are coming form rest_factory, so they don't need to be replicated.

2022-07-25 18:31 UTC, lonico commented on tests/unit/plugins/modules/test_na_ontap_security_audit.py
> +  NetAppONTAPSecuriyAudit as audit_module  # module under test
NetAppONTAPSecuriyAudit as audit_module, main as my_main

2022-07-25 18:31 UTC, lonico commented on tests/unit/plugins/modules/test_na_ontap_security_audit.py
> +  print('Info: %s' % exc.value.args[0]['msg'])
we have a new method, so we don't see set_module_args, or with pytest.raises
```
error= 'xxxx'
assert error in call_main(my_main, DEFAULT_ARGS, module_args, fail=True)['msg']
```
here is becomes:
```
assert error in call_main(my_main, {}, fail=True)['msg']

2022-07-25 18:31 UTC, lonico commented on tests/unit/plugins/modules/test_na_ontap_security_audit.py
> +def default_args():
replace this with 
```
DEFAULT_ARGS = {
    'hostname': '141.94.231.150',
    'username': 'admin',
    'https': 'true',
    'validate_certs': 'false',
    'password': 'Storage2020!',
    'use_rest': 'always'
}

2022-07-25 18:31 UTC, lonico commented on tests/unit/plugins/modules/test_na_ontap_security_audit.py
> +  args = dict(default_args())
```
    args = dict(DEFAULT_ARGS)
    del args['hostname']
    error = 'missing required arguments: hostname'
    assert error in call_main(my_main, args, fail=True)['msg']

2022-07-25 18:31 UTC, lonico commented on tests/unit/plugins/modules/test_na_ontap_security_audit.py
> +  assert create_and_apply(audit_module, default_args(), module_args)['changed']
assert create_and_apply(audit_module, DEFAULT_ARGS, module_args)['changed']

2023-07-20 17:45 UTC, closed without merging