Adding na_ontap_ems_destination
ansible-collections/netapp.ontap pull request #92
Opened 2022-08-13 18:36 UTC by bielawb

##### SUMMARY
Fixes: #35
Initial version of na_ontap_ems_destination.

##### ISSUE TYPE
- New Module Pull Request

##### COMPONENT NAME
 na_ontap_ems_destination

2022-08-15 17:34 UTC, lonico requested changes
looking great overall!

2022-08-15 17:34 UTC, lonico commented on plugins/modules/na_ontap_ems_destination.py
> +version_added: 21.22.0
21.23.0

2022-08-15 17:34 UTC, lonico commented on plugins/modules/na_ontap_ems_destination.py
> +short_description: NetApp ONTAP configuration for EMS event destinations.
destinations:  Does it support only one destination?

2022-08-15 17:34 UTC, lonico commented on plugins/modules/na_ontap_ems_destination.py
> +  - Configure EMS destinations. Currently certificate authentication for REST is not supported.
destinations: Does it support only one destination?

2022-08-15 17:34 UTC, lonico commented on plugins/modules/na_ontap_ems_destination.py
> +short_description: NetApp ONTAP configuration for EMS event destinations.
no `.` at end of line here.

2022-08-15 17:34 UTC, lonico commented on plugins/modules/na_ontap_ems_destination.py
> +      - Destination - content depends on the type
`.` at end of line.

2022-08-15 17:34 UTC, lonico commented on plugins/modules/na_ontap_ems_destination.py
> +      - List of filters that destination is linked to
`.` at end of line.

2022-08-15 17:34 UTC, lonico commented on plugins/modules/na_ontap_ems_destination.py
> +    """Create/ Modify/ Remove EMS destinations"""
no space after /

2022-08-15 17:34 UTC, lonico commented on plugins/modules/na_ontap_ems_destination.py
> +        for filter in filters:
use a list comprehension
```
return [{'name': filter} for filter in filters]

2022-08-15 17:34 UTC, lonico commented on plugins/modules/na_ontap_ems_destination.py
> +                self.module.fail_json(msg='Error: unexpected ems destination body: %s, KeyError on %s' % (str(record), str(exc)))
str is not necessary as it is implied by %s

2022-08-15 17:34 UTC, lonico commented on plugins/modules/na_ontap_ems_destination.py
> +            modify = self.na_helper.get_modified_attributes(current, self.parameters)
Our helper function will consider the list as unordered.  If the order matters for the filters, this may be a problem.   Otherwise, this is good as is.

2022-08-15 17:34 UTC, lonico commented on tests/unit/plugins/modules/test_na_ontap_ems_destination.py
> +    assert msg in expect_and_capture_ansible_exception(my_module_object.get_ems_destination, 'fail')['msg']
This test fails with
```
E           TypeError: get_ems_destination() takes exactly 2 arguments (1 given)
```
You need to add required parameters after 'fail':
```
assert msg in expect_and_capture_ansible_exception(my_module_object.get_ems_destination, 'fail', 'some_name')['msg']
```

2022-08-15 17:34 UTC, lonico commented on tests/unit/plugins/modules/test_na_ontap_ems_destination.py
> +    error = expect_and_capture_ansible_exception(my_obj.modify_ems_destination, 'fail')['msg']
same thing, 2 parameters are missing
```
assert msg in expect_and_capture_ansible_exception(my_module_object.modify_ems_destination, 'fail', 'some_name', {})['msg']

2022-08-15 20:00 UTC, bielawb commented on plugins/modules/na_ontap_ems_destination.py
> +  - Configure EMS destinations. Currently certificate authentication for REST is not supported.
Changed to singular - indeed, support is for a single destination.

2022-08-15 20:01 UTC, bielawb commented on plugins/modules/na_ontap_ems_destination.py
> +short_description: NetApp ONTAP configuration for EMS event destinations.
Fixed.

2022-08-15 20:01 UTC, bielawb commented on plugins/modules/na_ontap_ems_destination.py
> +      - Destination - content depends on the type
Fixed.

2022-08-15 20:01 UTC, bielawb commented on plugins/modules/na_ontap_ems_destination.py
> +      - List of filters that destination is linked to
Fixed.

2022-08-15 20:01 UTC, bielawb commented on plugins/modules/na_ontap_ems_destination.py
> +    """Create/ Modify/ Remove EMS destinations"""
Fixed. Also change to singular "destination".

2022-08-15 20:01 UTC, bielawb commented on plugins/modules/na_ontap_ems_destination.py
> +        for filter in filters:
Fixed.

2022-08-15 20:01 UTC, bielawb commented on plugins/modules/na_ontap_ems_destination.py
> +                self.module.fail_json(msg='Error: unexpected ems destination body: %s, KeyError on %s' % (str(record), str(exc)))
Fixed.

2022-08-15 20:02 UTC, bielawb commented on plugins/modules/na_ontap_ems_destination.py
> +            modify = self.na_helper.get_modified_attributes(current, self.parameters)
in my limited tests it worked as expected.

2022-08-15 20:03 UTC, bielawb commented on tests/unit/plugins/modules/test_na_ontap_ems_destination.py
> +    assert msg in expect_and_capture_ansible_exception(my_module_object.get_ems_destination, 'fail')['msg']
Clear, I was expecting something like that, but failed to spot that detail in the tests output.

2022-08-15 20:04 UTC, bielawb commented on tests/unit/plugins/modules/test_na_ontap_ems_destination.py
> +    error = expect_and_capture_ansible_exception(my_obj.modify_ems_destination, 'fail')['msg']
With empty modify, REST method would not be called, so I'm defining it before calling the method.

2022-08-16 19:01 UTC, lonico requested changes
Only updating the example and adding one instance of call_main is really required.
The rest is up to you.

2022-08-16 19:01 UTC, lonico commented on plugins/modules/na_ontap_ems_destination.py
> +    obj = NetAppOntapEmsDestination()
These 2 lines can be covered using `call_main`, see other comment.

2022-08-16 21:30 UTC, carchi8py commented on plugins/modules/na_ontap_ems_destination.py
> +        password: "{{password}}"
Can you include a absent example as well.

2022-08-16 22:29 UTC, bielawb commented on plugins/modules/na_ontap_ems_destination.py
> +      na_ontap_ems_destination:
Fixed

2022-08-16 22:29 UTC, bielawb commented on plugins/modules/na_ontap_ems_destination.py
> +        elements = dict(msg="Error: %s" % error)
Indeed - copied from somewhere else, but dropped whole dict building now.

2022-08-16 22:29 UTC, bielawb commented on tests/unit/plugins/modules/test_na_ontap_ems_destination.py
> +    error = create_module(my_module, DEFAULT_ARGS, module_args, fail=True)['msg']
Great, indeed got some additional hits.

2022-08-16 22:30 UTC, bielawb commented on plugins/modules/na_ontap_ems_destination.py
> +        password: "{{password}}"
Another example added.

2022-08-17 14:17 UTC, lonico approved these changes

2022-08-17 16:16 UTC, merged